name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  release:
    name: Create new release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: gh release create ${{ github.ref }} --draft --title "memory_addresses ${{ github.ref_name }}"
      - name: Create release
        run: |
          for FILE in README.md LICENSE-*; do
            gh release upload ${{ github.ref }} $FILE
          done
